import type { RoleDefinition } from "@clab/domain";

export const BUILTIN_ROLES: RoleDefinition[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    reportsTo: null,
    goals: ["Coordinate all agents", "Make strategic decisions", "Ensure mission success"],
    allowedActions: ["dispatch", "escalate", "decide", "approve", "create_wave", "abort"],
    blockedActions: [],
    requiredSkills: [],
    defaultEngine: "CLAUDE",
    reviewPolicy: "none",
    knowledgeScope: { reads: ["**/*"], writes: ["operations/**", "decisions/**"] },
    authorityLevel: "c_level",
  },
  {
    id: "builder",
    name: "Builder",
    reportsTo: "orchestrator",
    goals: ["Implement code changes", "Write tests", "Fix bugs"],
    allowedActions: ["write_code", "write_tests", "fix_bugs", "refactor", "run_tests"],
    blockedActions: ["deploy_prod", "modify_infra", "access_secrets"],
    requiredSkills: ["coding", "testing"],
    defaultEngine: "CODEX",
    reviewPolicy: "mandatory",
    knowledgeScope: { reads: ["src/**", "tests/**", "docs/**"], writes: ["src/**", "tests/**"] },
    authorityLevel: "individual",
  },
  {
    id: "architect",
    name: "Architect",
    reportsTo: "orchestrator",
    goals: ["Design system architecture", "Reduce technical risk", "Define interfaces"],
    allowedActions: ["create_design", "review_code", "write_code", "refactor", "restructure"],
    blockedActions: ["deploy_prod", "major_migration_execute"],
    requiredSkills: ["architecture-review", "interface-design"],
    defaultEngine: "CODEX",
    reviewPolicy: "optional",
    knowledgeScope: { reads: ["**/*"], writes: ["architecture/**", "src/**"] },
    authorityLevel: "manager",
  },
  {
    id: "pm",
    name: "PM",
    reportsTo: "orchestrator",
    goals: ["Decompose tasks", "Prioritize work", "Track progress"],
    allowedActions: ["decompose", "prioritize", "create_wave", "assign_task"],
    blockedActions: ["write_code", "deploy", "modify_infra"],
    requiredSkills: ["task-decomposition", "prioritization"],
    defaultEngine: "CLAUDE",
    reviewPolicy: "none",
    knowledgeScope: { reads: ["**/*"], writes: ["projects/**", "operations/**"] },
    authorityLevel: "manager",
  },
  {
    id: "reviewer",
    name: "Operations Reviewer",
    reportsTo: "orchestrator",
    goals: ["Verify code quality", "Catch bugs", "Ensure standards"],
    allowedActions: ["review", "verify", "approve", "reject", "run_tests"],
    blockedActions: ["write_code", "deploy", "delete_files"],
    requiredSkills: ["code-review", "testing"],
    defaultEngine: "CLAUDE",
    reviewPolicy: "none",
    knowledgeScope: { reads: ["**/*"], writes: ["operations/**"] },
    authorityLevel: "individual",
  },
  {
    id: "strategist",
    name: "Strategist",
    reportsTo: "orchestrator",
    goals: ["Analyze technical strategy", "Evaluate scope", "Assess risk"],
    allowedActions: ["analyze", "research", "recommend", "document"],
    blockedActions: ["write_code", "deploy", "modify_infra"],
    requiredSkills: ["strategic-analysis", "risk-assessment"],
    defaultEngine: "CODEX",
    reviewPolicy: "optional",
    knowledgeScope: { reads: ["**/*"], writes: ["architecture/**", "projects/**"] },
    authorityLevel: "individual",
  },
  {
    id: "research-analyst",
    name: "Research Analyst",
    reportsTo: "orchestrator",
    goals: ["Research topics", "Document findings", "Provide evidence"],
    allowedActions: ["research", "document", "browse_web", "analyze_data"],
    blockedActions: ["write_code", "deploy", "modify_infra"],
    requiredSkills: ["research", "documentation"],
    defaultEngine: "CODEX",
    reviewPolicy: "optional",
    knowledgeScope: { reads: ["**/*"], writes: ["knowledge/**", "docs/**"] },
    authorityLevel: "individual",
  },
];
