import type { SkillBundle } from "@clab/domain";

export const BUILTIN_SKILLS: SkillBundle[] = [
  {
    id: "coding",
    name: "Code Implementation",
    description: "Write, modify, and refactor code",
    inputs: ["task_description", "file_paths", "constraints"],
    steps: [
      "Read existing code in scope",
      "Plan implementation approach",
      "Write code changes",
      "Add or update tests",
      "Run existing tests",
      "Verify changes compile",
    ],
    outputs: ["modified_files", "test_results", "summary"],
    constraints: ["Follow existing code style", "Do not modify files outside scope"],
    version: "1.0.0",
  },
  {
    id: "testing",
    name: "Test Writing",
    description: "Write unit, integration, and e2e tests",
    inputs: ["source_files", "test_framework", "coverage_targets"],
    steps: [
      "Analyze source code for testable units",
      "Identify edge cases and error paths",
      "Write test cases",
      "Run tests and verify pass",
      "Check coverage meets targets",
    ],
    outputs: ["test_files", "coverage_report", "summary"],
    constraints: ["Use project's existing test framework", "Aim for meaningful coverage, not just line count"],
    version: "1.0.0",
  },
  {
    id: "architecture-review",
    name: "Architecture Review",
    description: "Review system design and identify risks",
    inputs: ["repo_context", "current_constraints", "change_scope"],
    steps: [
      "Inspect existing interfaces and boundaries",
      "Identify coupling and failure domains",
      "Evaluate change impact on system properties",
      "Propose minimal viable change",
      "Document risks and migration steps",
    ],
    outputs: ["design_note", "risk_list", "migration_steps"],
    constraints: ["Read-only analysis", "Focus on structural concerns"],
    version: "1.0.0",
  },
  {
    id: "interface-design",
    name: "Interface Design",
    description: "Design APIs and system interfaces",
    inputs: ["requirements", "existing_interfaces", "constraints"],
    steps: [
      "Analyze requirements and use cases",
      "Survey existing interface patterns",
      "Design interface contract",
      "Define error handling strategy",
      "Document interface specification",
    ],
    outputs: ["interface_spec", "examples", "migration_guide"],
    constraints: ["Backward compatibility unless explicitly breaking"],
    version: "1.0.0",
  },
  {
    id: "task-decomposition",
    name: "Task Decomposition",
    description: "Break complex tasks into manageable subtasks",
    inputs: ["objective", "constraints", "team_capacity"],
    steps: [
      "Understand the objective fully",
      "Identify independent work streams",
      "Define subtask boundaries and dependencies",
      "Assign roles to subtasks",
      "Estimate effort and set priorities",
    ],
    outputs: ["subtask_list", "dependency_graph", "priority_order"],
    constraints: ["Each subtask should be completable by one role"],
    version: "1.0.0",
  },
  {
    id: "code-review",
    name: "Code Review",
    description: "Review code changes for quality and correctness",
    inputs: ["diff", "context", "acceptance_criteria"],
    steps: [
      "Read the diff in full",
      "Check for correctness and logic errors",
      "Verify style and convention compliance",
      "Check for security issues",
      "Verify tests cover changes",
      "Provide actionable feedback",
    ],
    outputs: ["review_result", "issues_found", "suggestions"],
    constraints: ["Be specific and constructive", "Reference line numbers"],
    version: "1.0.0",
  },
  {
    id: "research",
    name: "Research & Analysis",
    description: "Research topics and produce structured findings",
    inputs: ["research_question", "scope", "existing_knowledge"],
    steps: [
      "Define research scope and methodology",
      "Gather information from available sources",
      "Analyze and synthesize findings",
      "Identify key insights and patterns",
      "Document findings with evidence",
    ],
    outputs: ["research_report", "key_findings", "references"],
    constraints: ["Cite sources", "Distinguish facts from opinions"],
    version: "1.0.0",
  },
  {
    id: "documentation",
    name: "Documentation",
    description: "Write and update technical documentation",
    inputs: ["subject", "audience", "existing_docs"],
    steps: [
      "Understand the subject matter",
      "Identify target audience needs",
      "Write clear, structured documentation",
      "Add examples and diagrams where helpful",
      "Cross-link with related documents",
    ],
    outputs: ["documentation_files", "index_updates"],
    constraints: ["Keep docs close to code", "Update existing docs rather than creating duplicates"],
    version: "1.0.0",
  },
  {
    id: "strategic-analysis",
    name: "Strategic Analysis",
    description: "Evaluate strategic options and risks",
    inputs: ["problem_statement", "constraints", "options"],
    steps: [
      "Frame the decision clearly",
      "List and evaluate alternatives",
      "Assess risks for each option",
      "Recommend with rationale",
      "Define success metrics",
    ],
    outputs: ["analysis_report", "recommendation", "risk_matrix"],
    constraints: ["Consider long-term implications", "Be explicit about trade-offs"],
    version: "1.0.0",
  },
  {
    id: "risk-assessment",
    name: "Risk Assessment",
    description: "Identify and evaluate technical and operational risks",
    inputs: ["change_scope", "system_context", "constraints"],
    steps: [
      "Identify risk categories",
      "Assess likelihood and impact",
      "Propose mitigations",
      "Prioritize by severity",
      "Document risk register",
    ],
    outputs: ["risk_register", "mitigation_plan"],
    constraints: ["Be concrete and specific", "Include both technical and operational risks"],
    version: "1.0.0",
  },
];
