apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clab

commonLabels:
  app.kubernetes.io/part-of: clab-platform
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - postgres.yaml
  - nats.yaml
  - api-gateway.yaml
  - orchestrator.yaml
  - runtime-manager.yaml
  - workers.yaml
  - review-service.yaml
  - dashboard.yaml
